#!/usr/bin/env python3
"""Run opencode over dictionary origination batch files.

This script consumes the manifest generated by dictionary_origination_batch.py
and asks opencode to produce one *_results.jsonl file per batch.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import shlex
import subprocess
import sys
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_DIR = SCRIPT_DIR.parent
DEFAULT_MODEL = "mimo/mimo-v2.5-pro"
DEFAULT_AGENT = "build"
DEFAULT_MANIFEST = REPO_DIR / "var/origination_batches/manifest.json"
DEFAULT_DB = REPO_DIR / "Resources/dic_.db"
DEFAULT_CONCURRENCY = 3
DEFAULT_TIMEOUT_SECONDS = 1200


@dataclass(frozen=True)
class BatchTask:
    number: int
    prompt_file: Path
    batch_file: Path
    result_file: Path
    log_file: Path
    command: list[str]
    printable_command: str


@dataclass(frozen=True)
class BatchOutcome:
    number: int
    ok: bool
    message: str


def load_manifest(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise SystemExit(f"Manifest not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit(f"Manifest must be a JSON list: {path}")
    return data


def resolve_path(raw: str, base_dirs: list[Path], manifest_dir: Path) -> Path:
    path = Path(raw)
    if path.is_absolute():
        return path

    candidates = [(base_dir / path).resolve() for base_dir in base_dirs]
    candidates.append((manifest_dir / path.name).resolve())

    for candidate in candidates:
        if candidate.exists() or candidate.parent.exists():
            return candidate

    return candidates[0]


def batch_number(item: dict[str, Any]) -> int:
    return int(item.get("batch", 0))


def selected_batches(
    manifest: list[dict[str, Any]],
    start: int | None,
    end: int | None,
    limit: int | None,
) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for item in manifest:
        number = batch_number(item)
        if start is not None and number < start:
            continue
        if end is not None and number > end:
            continue
        selected.append(item)
        if limit is not None and len(selected) >= limit:
            break
    return selected


def build_message(prompt_file: Path, batch_file: Path, result_file: Path) -> str:
    return f"""请严格按附件中的 prompt 处理本批词典数据。

附件：
- prompt: {prompt_file}
- input JSONL: {batch_file}

请读取 input JSONL 的每一行，为每条记录生成 origination，然后把结果保存到：
{result_file}

硬性要求：
- 你必须实际创建/覆盖上面的结果文件；不要只在最终回答里打印 JSONL。
- 请使用文件写入能力保存结果文件。
- 输出文件必须是 JSONL，一行一个 JSON object。
- 每行只包含 id、word、origination 三个字段。
- id 和 word 必须和输入记录一致。
- origination 必须保留 [[word]] 作为相关词内链标记。
- 请优先用 Python 的 json.dumps(..., ensure_ascii=False) 或等价 JSON 序列化方式写文件，确保中文说明里的引号、换行等字符都被正确转义。
- origination 文本里尽量使用中文引号“”而不是未转义的英文双引号。
- origination 文本中禁止出现未转义的英文双引号 "；需要引用含义时一律用中文引号“”。
- 不要修改数据库，不要修改输入 batch，不要输出 Markdown 代码块。
- 如果无法确认可靠词源，不要编造来源；改用“记忆上可理解为”或“可以这样记”。
- 保存文件后，确认结果文件存在，并确认输出行数等于输入 JSONL 行数，然后停止。
"""


def command_for_batch(args: argparse.Namespace, prompt_file: Path, batch_file: Path, result_file: Path) -> list[str]:
    command = [
        "opencode",
        "run",
        "--model",
        args.model,
        "--dir",
        str(args.project_dir),
        "--title",
        f"origination batch {batch_file.stem}",
        "--file",
        str(prompt_file),
        "--file",
        str(batch_file),
    ]
    command.extend(["--agent", args.agent])
    if args.variant:
        command.extend(["--variant", args.variant])
    if args.dangerously_skip_permissions:
        command.append("--dangerously-skip-permissions")
    command.append(build_message(prompt_file, batch_file, result_file))
    return command


def validate_result(import_script: Path, db_path: Path, result_file: Path, *, quiet: bool = False) -> bool:
    command = [
        sys.executable,
        str(import_script),
        "import",
        "--db",
        str(db_path),
        "--results",
        str(result_file),
        "--dry-run",
    ]
    completed = subprocess.run(command, text=True, capture_output=True)
    if completed.returncode == 0:
        if not quiet:
            print(completed.stdout.strip())
        return True

    if not quiet:
        print(completed.stdout, end="")
        print(completed.stderr, end="", file=sys.stderr)
    return False


def print_locked(lock: threading.Lock, message: str, *, error: bool = False) -> None:
    with lock:
        print(message, file=sys.stderr if error else sys.stdout)


def should_retry_failure(args: argparse.Namespace, completed: subprocess.CompletedProcess[str]) -> bool:
    if args.retry_all_failures:
        return True

    combined = f"{completed.stdout}\n{completed.stderr}".lower()
    retry_markers = [
        "429",
        "rate limit",
        "ratelimit",
        "too many requests",
        "temporarily unavailable",
        "timeout",
        "timed out",
    ]
    return any(marker in combined for marker in retry_markers)


def opencode_reported_error(completed: subprocess.CompletedProcess[str]) -> bool:
    combined = f"{completed.stdout}\n{completed.stderr}".lower()
    error_markers = [
        "providermodelnotfounderror",
        "model not found",
    ]
    return any(marker in combined for marker in error_markers)


def retry_delay(args: argparse.Namespace, attempt_index: int) -> float:
    return args.retry_base_delay * (2 ** attempt_index)


def run_single_batch(
    args: argparse.Namespace,
    task: BatchTask,
    project_dir: Path,
    import_script: Path,
    db_path: Path,
    print_lock: threading.Lock,
) -> BatchOutcome:
    task.result_file.parent.mkdir(parents=True, exist_ok=True)
    task.log_file.parent.mkdir(parents=True, exist_ok=True)
    log_parts: list[str] = [f"$ {task.printable_command}\n"]

    for attempt in range(args.retries + 1):
        label = f"[batch {task.number:04d}]"
        if attempt == 0:
            print_locked(print_lock, f"{label} running opencode -> {task.result_file}")
        else:
            print_locked(print_lock, f"{label} retry {attempt}/{args.retries} -> {task.result_file}")

        process = subprocess.Popen(
            task.command,
            cwd=project_dir,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        started_at = time.monotonic()
        completed: subprocess.CompletedProcess[str] | None = None

        while True:
            return_code = process.poll()
            if return_code is not None:
                stdout, stderr = process.communicate()
                completed = subprocess.CompletedProcess(task.command, return_code, stdout, stderr)
                break

            if task.result_file.exists():
                result_ok = args.no_validate or validate_result(import_script, db_path, task.result_file, quiet=True)
                if result_ok:
                    process.terminate()
                    try:
                        stdout, stderr = process.communicate(timeout=10)
                    except subprocess.TimeoutExpired:
                        process.kill()
                        stdout, stderr = process.communicate()
                    log_parts.append(
                        f"\nATTEMPT {attempt + 1}\nTERMINATED AFTER VALID RESULT\n"
                        f"\nSTDOUT\n{stdout}\n\nSTDERR\n{stderr}\n"
                    )
                    task.log_file.write_text("".join(log_parts), encoding="utf-8")
                    return BatchOutcome(task.number, True, "validated")

            if time.monotonic() - started_at >= args.timeout_seconds:
                process.kill()
                stdout, stderr = process.communicate()
                log_parts.append(
                    f"\nATTEMPT {attempt + 1}\nTIMEOUT after {args.timeout_seconds}s\n"
                    f"\nSTDOUT\n{stdout}\n\nSTDERR\n{stderr}\n"
                )
                task.log_file.write_text("".join(log_parts), encoding="utf-8")
                if task.result_file.exists():
                    if args.no_validate or validate_result(import_script, db_path, task.result_file):
                        return BatchOutcome(task.number, True, "validated after timeout")
                    return BatchOutcome(task.number, False, "validation failed after timeout")
                if attempt < args.retries:
                    delay = retry_delay(args, attempt)
                    print_locked(print_lock, f"{label} timed out; retrying in {delay:.1f}s", error=True)
                    time.sleep(delay)
                    continue
                return BatchOutcome(task.number, False, f"timed out after {args.timeout_seconds}s, see {task.log_file}")

            time.sleep(5)

        assert completed is not None

        log_parts.append(
            f"\nATTEMPT {attempt + 1}\nRETURN CODE {completed.returncode}\n"
            f"\nSTDOUT\n{completed.stdout}\n\nSTDERR\n{completed.stderr}\n"
        )
        task.log_file.write_text("".join(log_parts), encoding="utf-8")

        if completed.returncode != 0 or opencode_reported_error(completed):
            if attempt < args.retries and should_retry_failure(args, completed):
                delay = retry_delay(args, attempt)
                print_locked(print_lock, f"{label} transient failure; retrying in {delay:.1f}s")
                time.sleep(delay)
                continue
            return BatchOutcome(task.number, False, f"opencode failed, see {task.log_file}")

        if not task.result_file.exists():
            fallback = task.result_file.with_suffix(task.result_file.suffix + ".stdout.txt")
            fallback.write_text(completed.stdout, encoding="utf-8")
            if attempt < args.retries:
                delay = retry_delay(args, attempt)
                print_locked(
                    print_lock,
                    f"{label} result file missing; stdout saved to {fallback}; retrying in {delay:.1f}s",
                    error=True,
                )
                time.sleep(delay)
                continue
            return BatchOutcome(task.number, False, f"result file was not created; stdout saved to {fallback}")

        if args.no_validate:
            return BatchOutcome(task.number, True, "done")

        if validate_result(import_script, db_path, task.result_file):
            return BatchOutcome(task.number, True, "validated")

        return BatchOutcome(task.number, False, "validation failed")

    return BatchOutcome(task.number, False, "exhausted retries")


def prepare_tasks(
    args: argparse.Namespace,
    batches: list[dict[str, Any]],
    path_bases: list[Path],
    manifest_dir: Path,
    log_dir: Path,
    import_script: Path,
) -> tuple[list[BatchTask], int]:
    failures = 0
    tasks: list[BatchTask] = []

    for item in batches:
        number = batch_number(item)
        prompt_file = resolve_path(str(item["prompt"]), path_bases, manifest_dir)
        batch_file = resolve_path(str(item["input"]), path_bases, manifest_dir)
        result_file = resolve_path(str(item["suggested_result"]), path_bases, manifest_dir)
        log_file = log_dir / f"batch_{number:04d}_opencode.log"

        if result_file.exists() and not args.force:
            print(f"[batch {number:04d}] skip existing result: {result_file}")
            if args.validate_existing:
                if not validate_result(import_script, args.db.resolve(), result_file):
                    failures += 1
            continue

        if not prompt_file.exists():
            print(f"[batch {number:04d}] missing prompt: {prompt_file}", file=sys.stderr)
            failures += 1
            continue
        if not batch_file.exists():
            print(f"[batch {number:04d}] missing input: {batch_file}", file=sys.stderr)
            failures += 1
            continue

        command = command_for_batch(args, prompt_file, batch_file, result_file)
        printable = " ".join(shlex.quote(part) for part in command)

        if args.dry_run:
            print(f"[batch {number:04d}] {printable}")
            continue

        tasks.append(
            BatchTask(
                number=number,
                prompt_file=prompt_file,
                batch_file=batch_file,
                result_file=result_file,
                log_file=log_file,
                command=command,
                printable_command=printable,
            )
        )

    return tasks, failures


def run_batches(args: argparse.Namespace) -> int:
    project_dir = args.project_dir.resolve()
    invocation_dir = Path.cwd().resolve()
    manifest_path = args.manifest.resolve()
    manifest_dir = manifest_path.parent
    manifest = load_manifest(manifest_path)
    batches = selected_batches(manifest, args.start, args.end, args.limit)

    if not batches:
        print("No batches selected.")
        return 0

    import_script = (SCRIPT_DIR / "dictionary_origination_batch.py").resolve()
    if not import_script.exists():
        print(f"Import helper not found: {import_script}", file=sys.stderr)
        return 1

    path_bases = [project_dir, invocation_dir]
    log_dir = args.log_dir.resolve()
    log_dir.mkdir(parents=True, exist_ok=True)

    tasks, failures = prepare_tasks(args, batches, path_bases, manifest_dir, log_dir, import_script)

    if args.dry_run:
        print("Dry run complete.")
        return 0 if failures == 0 else 1

    if not tasks:
        if failures:
            print(f"Finished with {failures} failed batch(es).", file=sys.stderr)
            return 1
        print("No runnable batches selected.")
        return 0

    print(f"Running {len(tasks)} batch(es) with concurrency={args.concurrency}.")
    print_lock = threading.Lock()
    db_path = args.db.resolve()

    if args.stop_on_error and args.concurrency > 1:
        print(
            "Note: --stop-on-error stops scheduling new work, but already running concurrent batches may finish.",
            file=sys.stderr,
        )

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as executor:
        pending_tasks = iter(tasks)
        futures: dict[concurrent.futures.Future[BatchOutcome], BatchTask] = {}
        should_stop = False

        def submit_next() -> None:
            try:
                task = next(pending_tasks)
            except StopIteration:
                return
            future = executor.submit(
                run_single_batch,
                args,
                task,
                project_dir,
                import_script,
                db_path,
                print_lock,
            )
            futures[future] = task

        for _ in range(args.concurrency):
            submit_next()

        while futures:
            done, _ = concurrent.futures.wait(
                futures,
                return_when=concurrent.futures.FIRST_COMPLETED,
            )
            for future in done:
                task = futures.pop(future)
                try:
                    outcome = future.result()
                except Exception as exc:  # pragma: no cover - defensive CLI guard
                    failures += 1
                    print(f"[batch {task.number:04d}] crashed: {exc}", file=sys.stderr)
                    outcome = BatchOutcome(task.number, False, str(exc))

                if outcome.ok:
                    print(f"[batch {outcome.number:04d}] {outcome.message}")
                else:
                    failures += 1
                    print(f"[batch {outcome.number:04d}] {outcome.message}", file=sys.stderr)
                    if args.stop_on_error:
                        should_stop = True

                if not should_stop:
                    submit_next()

    if failures:
        print(f"Finished with {failures} failed batch(es).", file=sys.stderr)
        return 1

    print("All selected batches completed.")
    return 0


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run opencode/Mimo over exported dictionary origination batches.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  # Show this help
  ./scripts/run_opencode_origination_batches.py -h

  # Print the opencode commands without running them
  ./scripts/run_opencode_origination_batches.py --limit 1 --dry-run

  # Process up to 3 batches at once; existing *_results.jsonl files are skipped
  ./scripts/run_opencode_origination_batches.py --concurrency 3

  # Conservative run: lower concurrency, fewer retries, 10 minute timeout per batch
  ./scripts/run_opencode_origination_batches.py --concurrency 1 --retries 1 --timeout-seconds 600

  # Process only batch 2 through batch 10, inclusive
  ./scripts/run_opencode_origination_batches.py --start 2 --end 10

  # Resume from batch 11 and stop on the first failed batch
  ./scripts/run_opencode_origination_batches.py --start 11 --stop-on-error
""",
    )
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Path to manifest.json generated by the export script")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB, help="Dictionary DB used for result validation")
    parser.add_argument("--project-dir", type=Path, default=REPO_DIR, help="Workspace directory passed to opencode --dir")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="opencode model name, e.g. mimo/mimo-v2.5-pro")
    parser.add_argument("--agent", default=DEFAULT_AGENT, help="opencode agent name; build can write result files")
    parser.add_argument("--variant", help="Optional model variant/reasoning effort")
    parser.add_argument("--log-dir", type=Path, default=Path("var/opencode_batch_logs"))
    parser.add_argument("--start", type=int, help="First batch number to process")
    parser.add_argument("--end", type=int, help="Last batch number to process")
    parser.add_argument("--limit", type=int, help="Maximum number of selected batches to process")
    parser.add_argument("--concurrency", type=int, default=DEFAULT_CONCURRENCY, help="Number of opencode batches to run at the same time")
    parser.add_argument("--retries", type=int, default=3, help="Retries for transient opencode failures such as 429/rate limits")
    parser.add_argument("--retry-base-delay", type=float, default=8.0, help="Initial retry delay in seconds; doubles each retry")
    parser.add_argument("--retry-all-failures", action="store_true", help="Retry any opencode nonzero exit, not only 429/rate-limit-like failures")
    parser.add_argument("--timeout-seconds", type=float, default=DEFAULT_TIMEOUT_SECONDS, help="Maximum seconds to allow one opencode batch attempt to run")
    parser.add_argument("--force", action="store_true", help="Re-run even if result file exists")
    parser.add_argument("--dry-run", action="store_true", help="Print opencode commands without running them")
    parser.add_argument("--no-validate", action="store_true", help="Do not dry-run import results after each batch")
    parser.add_argument("--validate-existing", action="store_true", help="Validate skipped existing result files")
    parser.add_argument("--stop-on-error", action="store_true")
    parser.add_argument(
        "--dangerously-skip-permissions",
        action="store_true",
        help="Pass opencode's auto-approve flag. Use only in a trusted workspace.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)
    if args.limit is not None and args.limit <= 0:
        parser.error("--limit must be positive")
    if args.concurrency <= 0:
        parser.error("--concurrency must be positive")
    if args.retries < 0:
        parser.error("--retries must be zero or positive")
    if args.retry_base_delay < 0:
        parser.error("--retry-base-delay must be zero or positive")
    if args.timeout_seconds <= 0:
        parser.error("--timeout-seconds must be positive")
    if args.start is not None and args.end is not None and args.start > args.end:
        parser.error("--start must be less than or equal to --end")
    return run_batches(args)


if __name__ == "__main__":
    raise SystemExit(main())
